language: cpp

os: linux
dist: trusty
sudo: required

before_install:
  - tools/apt-get-install-deps.sh
  - deps/jerry/tools/apt-get-install-deps.sh
  - deps/jerry/tools/apt-get-install-qemu-arm.sh

install:

script: "tools/build.py $OPTS"

env:
  - OPTS="--buildtype=debug"
  - OPTS="--buildtype=release"
  - OPTS="--jerry-lto"
  - OPTS="--no-snapshot"
  - OPTS="--target-arch=arm --target-board=rpi2"
